= Neo4j JDBC Driver Performance Test
A program that tests the performance of the JDBC driver for Neo4j 3.0.

This simple program stresses a Neo4j server with a threadpool of threads executing various types of queries. Each query is called for a specified period of time and at the end the program elaborates the number of queries and the average query execution time of each thread. At the end it shows the results.

== QUERIES
==== User create (2%)
[source,java]
----
MERGE (u:User {id:{1}}) ON CREATE SET u.name = {2}, u.age={3}
----

==== Relationship create (8%)
[source,java]
----
MATCH (u:User {id:{1}}), (f:User {id:{2}}) MERGE (u)-[:FRIEND]-(f);
----

==== User match (18%)
[source,java]
----
MATCH (u:User {id:{1}}) RETURN u;
----

==== Relationship match (63%)
[source,java]
----
MATCH (u:User {id:{1}})-[:FRIEND]-(f) RETURN f.id;
----
==== Suggestion (9%)
[source,java]
----
MATCH (u:User {id:{1}})-[:FRIEND]-(f)-[:FRIEND]-(fof) WHERE NOT (u)-[:FRIEND]-(fof)  WITH fof, count(*) as score  ORDER BY score DESC LIMIT 10 RETURN fof.id as fof, score;
----

== SETUP
To setup this test you need to have a running Neo4j 3.0 with a known username/password, build the software (mvn clean install) and then launch the jar-with-dependencies inside the target folder.

== ATTRIBUTES
This program supports various attributes for its tuning:

==== --protocol <choice> (-p) [default: BOLT]
Specifies which access method should be used between BOLT, HTTP or DRIVER (https://github.com/neo4j/neo4j-java-driver[neo4j-java-driver])

==== --db-url <url> (-d) [default: localhost]
Requires the url to use for database access in the format <host>?user=<username>,password=<password>

==== --threads <n> (-n) [default: 100]
Specifies the total number of threads to run

==== --time <n> (-t) [default: 10]
Specifies the number of seconds the test will run

==== --force-clear (-f)
Specifies wether to clear the database or not. If you don't use this option and the database is not empty the test won't run.

== LICENSE

Copyright (c) 2016 http://www.larus-ba.it[LARUS Business Automation] 

The "Neo4j JDBC Driver Performance Test" is licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.

You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.
